steps:

- id: 'Artifacts Registry'
  name: 'gcr.io/cloud-builders/gcloud'
  script: |
    gcloud artifacts print-settings npm \
      --project=zero65 \
      --repository=npm \
      --location=asia-south1 \
      --scope=@zero65 >> .npmrc

- id: 'Npm Install'
  name: 'gcr.io/cloud-builders/npm'
  script: |
    npx google-artifactregistry-auth
    npm install --omit=dev

- id: 'Docker Build'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-south1-docker.pkg.dev/zero65/docker/gcloud:$COMMIT_SHA', '-f', 'Dockerfile', '.' ]

- id: 'Docker Push'
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'asia-south1-docker.pkg.dev/zero65/docker/gcloud:$COMMIT_SHA' ]

- id: 'Run Deploy'
  name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy', 'gcloud',
    '--image', 'asia-south1-docker.pkg.dev/zero65/docker/gcloud:$COMMIT_SHA',
    '--region', 'asia-south1',
    '--platform', 'managed'
  ]
